//
//  AWSNoSQLHashtag.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class AWSNoSQLHashtag: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _name: String?
    
    class func dynamoDBTableName() -> String {

        return "warranty-mobilehub-1867399923-AWSNoSQLHashtag"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_name" : "name",
        ]
    }
}
