//
//  AWSNoSQLWarranty.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class AWSNoSQLWarranty: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _docImageBinary: Set<Data>?
    var _docImageLink: Set<String>?
    var _duration: NSNumber?
    var _email: String?
    var _hashtag: String?
    var _phone: String?
    var _productImageBinary: Set<Data>?
    var _productImageLink: Set<String>?
    var _productThumbnailLink: String?
    var _protectAt: String?
    var _uploadAt: String?
    
    class func dynamoDBTableName() -> String {

        return "warranty-mobilehub-1867399923-AWSNoSQLWarranty"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_docImageBinary" : "docImageBinary",
               "_docImageLink" : "docImageLink",
               "_duration" : "duration",
               "_email" : "email",
               "_hashtag" : "hashtag",
               "_phone" : "phone",
               "_productImageBinary" : "productImageBinary",
               "_productImageLink" : "productImageLink",
               "_productThumbnailLink" : "productThumbnailLink",
               "_protectAt" : "protectAt",
               "_uploadAt" : "uploadAt",
        ]
    }
}
